services:
  postgres:
    image: postgres:15
    container_name: postgres-antipattern-test
    environment:
      POSTGRES_DB: antipattern_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-antipatterns-detector.sql:/docker-entrypoint-initdb.d/01-antipatterns-detector.sql:ro
      - ./setup.sql:/docker-entrypoint-initdb.d/02-setup.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d antipattern_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: